# デバイス設定
device.pv-controller:
  com-port: "ttyUSB0"
  unit-id: 1

# サービス設定
service:
  # Ambientのチャネル接続設定
  ambient:
    channel-id: 99999
    read-key: "****************"
    write-key: "****************"

  # Nicehash APIの接続設定
  ## org-id: オーガニゼーションID
  ## api-key: APIキー
  ## api-secret: API秘密キー
  ## rig-id: リグID
  nicehash:
    org-id: "************************************"
    api-key: "************************************"
    api-secret: "************************************************************************"
    rig-id: "************************"

# 制御パラメータ
control:
  power:
    # 電源ONする条件(OR)
    ## stage: 充電ステージに応じて制御(BOOST/EQULIZATION/FLOAT/NO_CHARGING)
    ## soc: バッテリー残量に応じて制御(91%目安) ※SOCの値はあまりあてにならない
    ## voltage: 電圧に応じで制御(バッテリーの種類に応じて要調整 - 開放型で29.1, 密閉型で28.8くらいが目安)
    power-on-condition:
      voltage: 29.1
      # soc: 91.0
      stage: EQULIZATION

    # 電源OFFする条件(OR)
    ## stage: 充電ステージに応じて制御(BOOST/EQULIZATION/FLOAT/NO_CHARGING)
    ## soc: バッテリー残量に応じて制御(30%目安) ※SOCの値はあまりあてにならない
    ## voltage: 電圧に応じで制御(24.0くらいが目安)
    power-off-condition:
      voltage: 24.0
      # soc: 30.0
      # stage: NO_CHARGING
  fan:
    # PC停止後、冷却FAN停止までの時間(分)
    power-off-duration: 10
    # 15分毎の冷却FAN動作時間(秒)
    duration: 20
  tdp:
    # TDPの調整感度(ワット) ※値を大きくするほど細かな発電量の変化に影響されにくくなる(20くらいが目安)
    hysteresis: 20
