# デバイス設定
device.pv-controller:
  com-port: "ttyUSB0"
  unit-id: 1

# サービス設定
service.ambient:
  channel-id: 99999
  read-key: "****************"
  write-key: "****************"

# 制御パラメータ
control.power:
  # 電源ONする条件(stage/soc/voltageのどれか一つ)
  ## stage: 充電ステージに応じて制御(Boost/Equlization/Float/No Charging)
  ## soc: バッテリー残量に応じて制御(91%目安) ※SOCの値はあまりあてにならない
  ## voltage: 電圧に応じで制御(バッテリーの種類に応じて要調整 - 開放型で29.2, 密閉型で28.8くらいが目安)
  power-on-condition:
    stage: Equlization
    # soc: 91.0
    # voltage: 29.2

  # 電源OFFする条件(stage/soc/voltageのどれか一つ)
  ## stage: 充電ステージに応じて制御(Boost/Equlization/Float/No Charging)
  ## soc: バッテリー残量に応じて制御(30%目安) ※SOCの値はあまりあてにならない
  ## voltage: 電圧に応じで制御(負荷100Wで24.1, 200Wで23.8くらいが目安)
  power-off-condition:
    # stage: No Charging
    # soc: 30.0
    voltage: 23.8
