# デバイス設定
device.pv-controller:
  com-port: "ttyUSB0"
  unit-id: 1

# サービス設定
service:
  # Ambientのチャネル接続設定
  ambient:
    channel-id: 99999
    read-key: "****************"
    write-key: "****************"

  # Nicehash APIの接続設定
  ## org-id: オーガニゼーションID
  ## api-key: APIキー
  ## api-secret: API秘密キー
  ## rig-id: リグID
  nicehash:
    org-id: "************************************"
    api-key: "************************************"
    api-secret: "************************************************************************"
    rig-id: "************************"

# 制御パラメータ
control:
  power:
    # 電源ONする条件(OR)
    ## voltage: 電圧(V)に応じで制御(バッテリーの種類に応じて要調整 - 車用バッテリーは29.1, リン酸鉄リチウムイオンバッテリーは26.8くらいが目安)
    ## power: 発電電力(W)に応じて制御
    ## soc: バッテリー残量(%)に応じて制御(91目安) ※SOCの値はあまりあてにならない
    ## stage: 充電ステージに応じて制御(NO_CHARGING/BOOST/EQULIZATION/FLOAT)
    power-on-condition:
      voltage: 26.8
      power: 140.0
      # soc: 91.0
      stage: EQULIZATION

    # 電源OFFする条件(OR)
    ## voltage: 電圧(V)に応じで制御(バッテリーの種類に応じて要調整 - 車用バッテリーは24.0, リン酸鉄リチウムイオンバッテリーは25.9くらいが目安)
    ## power: 発電電力(W)に応じて制御
    ## soc: バッテリー残量(%)に応じて制御(30目安) ※SOCの値はあまりあてにならない
    ## stage: 充電ステージに応じて制御(NO_CHARGING/BOOST/EQULIZATION/FLOAT)
    power-off-condition:
      voltage: 25.9
      # power: 10.0
      # soc: 30.0
      # stage: NO_CHARGING
  fan:
    # PC停止後、冷却FAN停止までの時間(分)
    power-off-duration: 10
    # 15分毎の冷却FAN動作時間(秒)
    duration: 20
  tdp:
    # TDPの調整感度(W) ※値を大きくするほど細かな発電量の変化に影響されにくくなる(20くらいが目安)
    hysteresis: 20
